export { default as Navbar } from './navbar';
export { default as Testimonials } from './testimonials';
export { default as Hero } from './hero';
export { default as KeyFeatures } from './key-features';
export { default as Video } from './video';
export { default as About } from './about';
export { BottomCTA} from './BottomCTA';
export { Pricing } from './pricing';
export { default as FAQSection } from './faq';
export { default as LogoProof } from './LogoProof';
export { ProfileCard } from './ProfileCard';
export { CVSharingFeature } from './CVSharingFeature';
export { StatisticsBlock } from './StatisticsBlock';
export { MinimalFooter } from './MinimalFooter';
export { RotatingUrl } from './RotatingUrl';