export { default as Navbar } from './navbar';
export { default as Testimonials } from './testimonials';
export { default as Hero } from './hero';
export { default as KeyFeatures } from './key-features';
export { default as Video } from './video';
export { default as About } from './about';
export { default as BigCTA } from './big-cta';
export { default as Pricing } from './pricing';
export { default as FAQSection } from './faq';
export { default as LogoProof } from './LogoProof';
export { ProfileCard } from './ProfileCard';
export { CVSharingFeature } from './CVSharingFeature';